### ISSUE TITLE
Retrying submission in request_sender

### ISSUE THREAD

**Issue by tksakino** [plugaai/pytrthree#1]
It would be nice if we can put a large number of requests at once.
If we reach max number of simultaneous requests for reuters server, then the tool creates an event listener (waiting for job complete notification) to kick a callback which in turn sends another request via api.

**Comment by gusutabopb** [comment]
Just made a quick PR to fix this. I solved with a simple retry function instead of an event listener. Let me know what you think and will merge it into `master`.

I also renamed the issue, as it has nothing to do with asynchronous requests (`asyncio`/`aiohttp` stuff) and TRTH doesn't really support processing multiple HTTP requests concurrently (it usually throws the following error: `Authentication failed --> Your account is busy with another process.`).

**Comment by tksakino** [comment]
This does it!!
